### ISSUE TITLE
no file 

### ISSUE THREAD

**Issue by atif-zakaria** [motazsaad/Arabic-News#1]
the log:
python json2corpus.py
corpus name: 09/arabic.euronews.com/
processing /home/zakaria/Downloads/Arabic-News-master/corpora09/arabic.euronews.com/
# of files 0

number of files 0
{}
short count 0
.json
number of num_parts 18000
len of sub_lists 0
.txt
number of num_parts 18000
len of sub_lists 0
-------------------------------
corpus name: 09/bbc.com/
processing /home/zakaria/Downloads/Arabic-News-master/corpora09/bbc.com/
# of files 0

number of files 0
{}
short count 0
.json
number of num_parts 18000
len of sub_lists 0
.txt
number of num_parts 18000
len of sub_lists 0
-------------------------------
corpus name: 19/aljazeera.net/
processing /home/zakaria/Downloads/Arabic-News-master/corpora19/aljazeera.net/
# of files 0

number of files 0
{}
short count 0
.json
number of num_parts 18000
len of sub_lists 0
.txt
number of num_parts 18000
len of sub_lists 0
-------------------------------
corpus name: 19/arabic.rt.com/
processing /home/zakaria/Downloads/Arabic-News-master/corpora19/arabic.rt.com/
# of files 0

number of files 0
{}
short count 0
.json
number of num_parts 18000
len of sub_lists 0
.txt
number of num_parts 18000
len of sub_lists 0
-------------------------------
corpus name: 19/arabic.cnn.com/
processing /home/zakaria/Downloads/Arabic-News-master/corpora19/arabic.cnn.com/
# of files 0

number of files 0
{}
short count 0
.json
number of num_parts 18000
len of sub_lists 0
.txt
number of num_parts 18000
len of sub_lists 0
-------------------------------
all done

**Comment by motazsaad** [comment]
Extracted Corpus is in https://github.com/motazsaad/Arabic-News/tree/master/corpora 
So no need to run the script. 
json2corpus.py is to parse the crawled data using news-please python library

**Comment by atif-zakaria** [comment]
how can i run the script to crawl more news !

Le mar. 27 août 2019 à 04:18, Motaz Saad <notifications@github.com> a
écrit :
