### ISSUE TITLE
JSON file error

### ISSUE THREAD

**Issue by aljbri** [motazsaad/Arabic-News#2]
while I try to run the code I couldn't get any result, when I omit the part of the "JSONDecodeError" I get this message "JSONDecodeError: Extra data: line 1 column 3660 (char 3659)", the JSON file has an error with the JSON file "Syntax" which make hard to be parsed.

**Comment by motazsaad** [comment]
Please have a look at this notebook https://github.com/motazsaad/Arabic-News/blob/master/read_json_news.ipynb 
in addition, data in Pandas Dataframe CSV format can be found at https://www.kaggle.com/mksaad/arabic-news
